### ISSUE TITLE
Integration of Schedule Exam Pages (Admin/Teacher/Coordinator/Student)

### ISSUE THREAD

**Issue by harmonic-coder** [target-ready-2023/ResultsWebpage#22]
Integrating back end of Schedule Exam pages

1. User gets in to the page and able to browse through the page through different exam schedules - All
2. Able to import classes and subjects - Admin/Teacher/Coordinator
3. Able to add, edit or remove schedules - Admin/Teacher/Coordinator
4. Able to make the schedule active or inactive - Admin/Teacher/Coordinator
5. User able to see the relevant exam schedule - Student

**Comment by harmonic-coder** [comment]
24 July 2023

Started off on axios by integrating basic GET Calls

**Comment by harmonic-coder** [comment]
**25-July-2023**

Worked on the integration of Switch element in UI to the backend

This updates the status of a particular schedule as active/inactive 

Faced some issues while passing the request body

**Comment by harmonic-coder** [comment]
**26-July-2023**

Completed the put call integration for status updation
All issues resolved.
Will implement the same for individual subject status soon.

**Comment by Varsha4N** [comment]
**24-July-2023**
Tested all the API calls in my system.
Made the changes in the ui and started working on integration.

**25-July-2023**
Started integrating  the ADD SCHEDULE feature : implemented get-all classes API call and mapped it to the dropdown, and mapped schedule name dropdown and schedule type.
Had some issues with implementing add subject feature.

**26-July-2023**
Worked on integration of displaying the schedules of a class selected from dropdown , using: Get All classes API + Get All schedules by Class code.  And continued working on the ADD SCHEDULE feature.
Faced some issues.
Will Resolve the issues and complete the integration.

**Comment by harmonic-coder** [comment]
**27-JUL-2023**
1.Worked on deployment of code in netlify
Worked on integration and validations in the schedule page
2.Issues were encountered 
3.Will continue working on validations & integration and resolve the issues

**28-JUL-2023**
1. Resolved issues faced yesterday. Worked on the integration for student view of schedule page
2. Facing some issues in fetching data from backend
3. Will resolve them soon

**Comment by Varsha4N** [comment]
**27-JULY-2023**
1. Worked on Mapping class name with subject code and subject name, worked on results view page for student, helped for deploying the frontend.
2. Faced some issues.
3. Will continue work on the same

**28-JULY-2023**
1. Mapped class name with subject details through Json data from the API calls, displayed the mapped data through datagrid. added date and time attribute.
2. Facing some issues with storing the date and time.
3. Will resolve the issue and perform the POST Schedule request.

**Comment by harmonic-coder** [comment]
**31-Jul-2023**
1. Continued on the integration for student view of schedule page
2. Facing some issues on displaying the fetched data on datagrid
3. Will resolve them today

**Comment by harmonic-coder** [comment]
**01-Aug-2023**
1. Completed Integration of Student view for exam schedules
    Completed Delete call integration for admin/teacher/coordinator to delete a schedule
2. Resolved all issues faced regarding the above
3. Will close the issue after completion of PUT calls for the schedule

**Comment by Varsha4N** [comment]
**31-July-2023**

1. Continued working on the schedule page integration, by mapping all the data fetched from the apis and formatting them.
2. Issues with datagrid resolved.
3. Will continue work on the same

**Comment by Varsha4N** [comment]
**01-Aug-2023**

1. Completed the integration of ADD Schedule feature by using the POST call in schedule API and started working in update schedule.
2.  Resolved the issues faced.
3. Will continue work on the update feature of schedule page

**Comment by Varsha4N** [comment]
**02-Aug-2023**

1. Mapped the SubjectCode with SubjectName in the view/edit feature in the schedule update feature, worked on adding validations for the schedule page , formatted the tables and the buttons, and worked on merging the branches.
2.  Faced some issues.
3. Will work on validating the schedule pages.

**Comment by Varsha4N** [comment]
Replaced normal date time component with dateTime picker by mui and validated that part.

**Comment by harmonic-coder** [comment]
### **Week 5**


**_Varsha ->_**
+ Revised the drop downs to include Academic year to suit the API in Backend
+ Completed PUT call integrations for Date and Time in Schedule Page for admin


**_Varshini ->_**
+ Revised code to reflect the status of schedules/subjects from Backend on the UI
+ Completed PUT call integrations for Status Switch buttons
